import uuid
from typing import Any

from pgvector.sqlalchemy import HALFVEC
from sqlalchemy import Computed, ForeignKey, Index, Integer, Text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.constants import EMBEDDING_DIMENSIONS
from app.database.base import Base
from app.database.mixins import UUIDPrimaryKey, WorkspaceScoped


class DocumentChunk(Base, UUIDPrimaryKey, WorkspaceScoped):
    """A slice of an ingested document, with its embedding stored inline.

    SPEC-v2 D1 folded the v1 `embeddings` side table into this one: a 1:1
    join bought nothing and sat on the hottest query in the app.
    """

    __tablename__ = "document_chunks"
    __table_args__ = (
        Index(
            "ix_document_chunks_embedding",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "halfvec_cosine_ops"},
            postgresql_with={"m": "16", "ef_construction": "64"},
        ),
        Index("ix_document_chunks_tsv", "tsv", postgresql_using="gin"),
        Index("ix_document_chunks_document_id_chunk_index", "document_id", "chunk_index"),
    )

    document_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), index=True
    )
    text: Mapped[str] = mapped_column(Text)
    # NULL where the source format has no page concept until it is rendered
    # (.docx, .txt, .md) — only PDFs carry a real page number.
    page_no: Mapped[int | None] = mapped_column(Integer, default=None)
    chunk_index: Mapped[int] = mapped_column(Integer)
    embedding: Mapped[list[float]] = mapped_column(HALFVEC(EMBEDDING_DIMENSIONS))
    # Generated by Postgres from `text` rather than maintained in Python, so
    # it cannot drift out of sync with the column it indexes. Nothing in the
    # application ever writes it.
    tsv: Mapped[Any] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', text)", persisted=True)
    )
