"""chunks and jobs

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-24 23:21:32.570680

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import HALFVEC
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', HALFVEC(dim=768), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_document_chunks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_id_chunk_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    # The two indexes hybrid retrieval (Step 5) runs on: HNSW over the
    # halfvec embedding for cosine similarity, GIN over the generated tsvector
    # for exact terms. SPEC-v2 §4 lists both explicitly because autogenerate
    # would never guess the operator class or the m/ef_construction options.
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'})
    op.create_index('ix_document_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunks_workspace_id'), 'document_chunks', ['workspace_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='ingestion_job_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ingestion_jobs_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index('ix_ingestion_jobs_status_lease_until', 'ingestion_jobs', ['status', 'lease_until'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_workspace_id'), 'ingestion_jobs', ['workspace_id'], unique=False)
    op.create_index('uq_ingestion_jobs_document_id_active', 'ingestion_jobs', ['document_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'running')"))
    # NOTE: autogenerate also proposed dropping ck_documents_document_status,
    # ck_workspace_invites_invite_status, ck_workspace_invites_workspace_role
    # and ck_workspace_members_workspace_role here, and recreating them in
    # downgrade(). Spurious, and the same false positive that migration 0003
    # hit: alembic does not recognise the CHECK constraints that
    # str_enum()'s native_enum=False generates as belonging to the model, so
    # it reads them as orphans on every run. They are unchanged since 0002/0003
    # and must stay. Removed by hand after diffing against the live schema.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ingestion_jobs_document_id_active', table_name='ingestion_jobs', postgresql_where=sa.text("status IN ('pending', 'running')"))
    op.drop_index(op.f('ix_ingestion_jobs_workspace_id'), table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_status_lease_until', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_document_chunks_workspace_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'halfvec_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'})
    op.drop_index('ix_document_chunks_document_id_chunk_index', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
