"""agent

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-25 13:06:16.334050

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_log_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_index('ix_audit_log_workspace_id_created_at', 'audit_log', ['workspace_id', 'created_at'], unique=False)
    op.create_table('pending_actions',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('send_email', 'create_event', 'create_tasks', name='pending_action_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'refused', name='pending_action_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refusal_reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_pending_actions_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name=op.f('fk_pending_actions_initiated_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_pending_actions_thread_id_chat_threads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pending_actions_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_actions'))
    )
    op.create_index(op.f('ix_pending_actions_payload_hash'), 'pending_actions', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_pending_actions_workspace_id'), 'pending_actions', ['workspace_id'], unique=False)
    op.create_index('ix_pending_actions_workspace_id_status', 'pending_actions', ['workspace_id', 'status'], unique=False)
    # NOTE: the recurring spurious CHECK-constraint churn from autogenerate
    # (see migrations 0003-0005) was stripped here too. Alembic does not
    # recognise the constraints str_enum()'s native_enum=False generates as
    # belonging to the model, so it proposes dropping them on every run.
    #
    # The LangGraph checkpoint tables are deliberately NOT created here.
    # They belong to LangGraph, their layout changes with its version, and
    # hand-writing a migration for another library's internal schema breaks
    # on the next upgrade. AsyncPostgresSaver.setup() creates them at boot
    # instead, idempotently (SPEC-v2 table 17, "0006 (runtime)").
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_actions_workspace_id_status', table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_workspace_id'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_payload_hash'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index('ix_audit_log_workspace_id_created_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
