"""side effects

Tasks, calendar events and oauth credentials, plus two changes to
pending_actions: an `origin` column separating agent proposals (which have a
paused graph run behind them) from ones a person made directly, and a
`thread_id` that is now nullable because a manual proposal has no conversation.

The status CHECK constraint below is hand-written and has to be. Autogenerate
cannot see it: migrations/env.py filters type-bound CHECK constraints out of
the comparison, because alembic excludes them from the model side and Postgres
reflects them from the database side, so they can never agree. That filter is
what makes `alembic check` usable -- the cost is that adding a value to a
str_enum is a manual edit here. Adding one and forgetting this would produce a
migration that passes and an INSERT that fails at runtime.

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-25 15:08:47.470133

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.Enum('google_calendar', 'gmail', name='oauth_service', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), server_default='', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_credentials')),
    sa.UniqueConstraint('user_id', 'service', name=op.f('uq_oauth_credentials_user_id'))
    )
    op.create_table('calendar_events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('ics_uid', sa.String(length=255), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('guests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calendar_events_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_calendar_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events')),
    sa.UniqueConstraint('ics_uid', name=op.f('uq_calendar_events_ics_uid'))
    )
    op.create_index(op.f('ix_calendar_events_workspace_id'), 'calendar_events', ['workspace_id'], unique=False)
    op.create_index('ix_calendar_events_workspace_id_start_time', 'calendar_events', ['workspace_id', 'start_time'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'done', 'cancelled', name='task_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_tasks_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_messages.id'], name=op.f('fk_tasks_source_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_tasks_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_workspace_id'), 'tasks', ['workspace_id'], unique=False)
    op.create_index('ix_tasks_workspace_id_assigned_to', 'tasks', ['workspace_id', 'assigned_to'], unique=False)
    op.create_index('ix_tasks_workspace_id_status', 'tasks', ['workspace_id', 'status'], unique=False)
    op.add_column('pending_actions', sa.Column('origin', sa.Enum('agent', 'manual', name='pending_action_origin', native_enum=False, create_constraint=True, length=20), server_default='agent', nullable=False))
    op.alter_column('pending_actions', 'thread_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

    # Hand-written -- see the module docstring. PendingActionStatus gained
    # `failed` in Step 7: an approved action whose side effect did not happen
    # is not the same fact as one that did, and the column has to be able to
    # say so.
    # The bare name, not the full one: op.drop_constraint applies the naming
    # convention from app/database/base.py too, so passing the rendered name
    # would have it rendered a second time.
    op.drop_constraint('pending_action_status', 'pending_actions', type_='check')
    op.create_check_constraint(
        'pending_action_status',
        'pending_actions',
        "status IN ('pending', 'approved', 'rejected', 'executed', 'refused', 'failed')",
    )


def downgrade() -> None:
    # Narrowing the constraint first: a row already sitting at 'failed' would
    # otherwise make the new constraint unvalidatable, and the error would name
    # the constraint rather than the row that caused it.
    op.execute(
        """UPDATE pending_actions SET status = 'approved' WHERE status = 'failed'"""
    )
    # The bare name, not the full one: op.drop_constraint applies the naming
    # convention from app/database/base.py too, so passing the rendered name
    # would have it rendered a second time.
    op.drop_constraint('pending_action_status', 'pending_actions', type_='check')
    op.create_check_constraint(
        'pending_action_status',
        'pending_actions',
        "status IN ('pending', 'approved', 'rejected', 'executed', 'refused')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_actions', 'thread_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('pending_actions', 'origin')
    op.drop_index('ix_tasks_workspace_id_status', table_name='tasks')
    op.drop_index('ix_tasks_workspace_id_assigned_to', table_name='tasks')
    op.drop_index(op.f('ix_tasks_workspace_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_calendar_events_workspace_id_start_time', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_workspace_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_table('oauth_credentials')
    # ### end Alembic commands ###
