"""usage and limits

Two tables, and only one of them is in SPEC-v2's table reference.

`usage_events` is D8, as specified. `rate_limit_counters` is not in that list,
which names only usage_events for this migration -- but D15 chose "Postgres-
backed counters" over Redis for rate limiting, and counters have to be counted
somewhere. The alternative considered and rejected was to reuse usage_events
with a request-shaped row: that would put rejected requests into the ledger the
token budget is summed from, so being rate limited would spend budget. Two
tables that each mean one thing.

Neither carries a CHECK constraint written by hand. Both str_enum columns
generate theirs the usual way and migrations/env.py filters them out of future
autogenerate runs -- adding a value to UsageKind or RateLimitScope later needs
the manual drop/create pair described in 0007.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-26 23:08:57.097898

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_counters',
    sa.Column('bucket', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('request', 'register', name='rate_limit_scope', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_counters')),
    sa.UniqueConstraint('bucket', 'scope', 'window_start', name='uq_rate_limit_counters_window')
    )
    op.create_table('usage_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('chat', 'agent', 'embedding', name='usage_kind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_usage_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index(op.f('ix_usage_events_workspace_id'), 'usage_events', ['workspace_id'], unique=False)
    op.create_index('ix_usage_events_workspace_id_created_at', 'usage_events', ['workspace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_workspace_id_created_at', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_workspace_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('rate_limit_counters')
    # ### end Alembic commands ###
